catalyst/moodle-tool_excimer

.github/workflows/main.yml, classes/converter.php, classes/helper.php, classes/manager.php, classes/profile.php, classes/profile_table.php, db/install.xml, index.php, lang/en/tool_excimer.php, lib.php, profile.php, settings.php, templates/flamegraph.mustache, tests/tool_excimer_converter_test.php, tests/tool_excimer_profile_test.php
Supports automatically profiling through config setting.
Will save a profile if longer than the set time (will always save if uses FLAMEME)
Better support for downloading profile table.
Added descriptions to settings.
=> Issue #6: Automatically saving profiles

classes/profile.php, classes/task/expire_logs.php, db/tasks.php, tests/tool_excimer_profile_test.php
Added profile::purge_profiles_before_epoch_time()
Added profile::get_num_profiles()
Added unit test for tool_excimer_profile_test::test_purge_old_profiles()
=> Issue #7: Purging old profiles

classes/helper.php, classes/manager.php, classes/profile.php, classes/profile_table.php, db/install.xml, index.php, lang/en/tool_excimer.php, profile.php, templates/flamegraph.mustache, tests/tool_excimer_profile_test.php
Support for parameters FLAMEALL and FLAMEALLSTOP to switch profiling on and off respectively.
Added userid to profile DB table. #20
=> Issue #20: FLAMEALL support

classes/profile_table_page.php, flamegraph.json.php, lang/en/tool_excimer.php, profile.php, recent.php, settings.php, slowest.php
Added pages for recent and slowest profile reports.
Moved them to the Development Category.
Created profile_table_page class to handle common code.
There is a display issue with the breadcrumbs, but since that is to be fixed in issue #55, I thought to leave it for now.
=> Issue #39: New report pages

README.md, lang/en/tool_excimer.php, lib.php, settings.php
=> Detect and prevent profiling the class does not exist #68

classes/profile.php, classes/profile_table.php, classes/profile_table_page.php, delete.php, lang/en/tool_excimer.php, profile.php, templates/flamegraph.mustache
Issue #47
Added ability to delete profiles.
A 'Delete All' button added to profile list page.
A trash can icon added to profile row to delete individual profiles.
=> Issue #47: Delete Profiles

classes/profile.php, db/install.xml, db/upgrade.php, version.php
=> Update method to char(7) to ensure POST and other methods are stored #94

classes/helper.php, classes/profile.php, classes/profile_table.php, db/install.xml, db/upgrade.php, lang/en/tool_excimer.php, profile.php, templates/flamegraph.mustache, tests/tool_excimer_profile_test.php, version.php
Issue #53.
Added numsamples and datasize to tool_excimer_profiles db.
Displays on profile page.
=> Issue #53: Store number of samples and profile data size.

classes/output/renderer.php, classes/output/tabs.php, classes/profile_table_page.php, profile.php, recent.php, slowest.php, slowest_grouped.php, templates/flamegraph.mustache
Issue #77
Created a renderer class for the plugin
Created a tabs object to be used with renderer.
Refactored list pages to use tabs object.
Added tabs to the profile details page.
=> Issue #77: Add tabs to profile details page

profile.php, templates/flamegraph.mustache
=> Issue #79: Add delete all for request button to profile details page.

classes/grouped_profile_table.php, classes/helper.php, classes/profile_table.php, classes/profile_table_page.php
Issue #101
Action column is no longer included in downloads
Duration columns no longer have markup in downloads.
Group by request list no longer included link markup in downloads.
=> Issue #101: Removed web content from table downloads.

classes/output/tabs.php, classes/profile.php, classes/profile_table_page.php, lang/en/tool_excimer.php, recent.php, settings.php, slowest_grouped.php, unfinished.php
=> Issue #109: Added 'unfinished' report page.

classes/manager.php, tests/tool_excimer_profile_test.php
closes #91
Rearranged checking of flags for a micro-improvement.
=> Issue #91: Optimise flag checking

slowest.php
=> Issue #113: Fix sorting bug.

classes/grouped_profile_table.php, classes/profile_table.php, classes/profile_table_page.php, delete.php, lang/en/tool_excimer.php
closes #99
Added ability to delete according to a filter.
Added extra delete button to display table for deleting by filter.
=> Issue #99: Delete by filter

classes/helper.php, classes/manager.php, classes/profile.php, lang/en/tool_excimer.php, tests/tool_excimer_profile_test.php
=> Issue #84: Change REASON_AUTO to REASON_SLOW

classes/profile.php, db/install.xml, db/upgrade.php, flamegraph.json.php, tests/tool_excimer_profile_test.php, version.php
resolves #65
Added code to compress/decompress data stored in database.
Upgrade code includes compressing existing data.
Note: Uses default compression level.
=> Issue #65: compress flame data.

classes/profile.php, db/install.xml, db/upgrade.php, lang/en/tool_excimer.php, templates/flamegraph.mustache, version.php
I opted for the same format as the footer, e.g.
Closes #124
=> Add DB read/write ops to the profile #124

classes/manager.php, classes/profile.php
- Also check on cache setting and only set new values if values have changed from previous values.
=> Update cache on save instead of deleting to avoid race conditions #133

profile.php, templates/flamegraph.mustache
=> Issue #141: JS inclusion on profile page is done through Page API.

classes/privacy/provider.php, lang/en/tool_excimer.php
=> Issue #19: Added privacy classes

classes/grouped_profile_table.php, classes/manager.php, classes/profile.php, classes/script_metadata.php, classes/task/purge_fastest.php, classes/task_samples.php, db/install.xml, db/upgrade.php, delete.php, lang/en/tool_excimer.php, slowest.php, tests/tool_excimer_profile_test.php, tests/tool_excimer_script_metadata_test.php, version.php
resolves #112 
Decide to create a new PR to keep things neat.
=> Issue 112a wip

classes/flamed3_node.php
path root from closure file names
=> Small update: Change flamenode::extract_name_from_trace() to strip

db/upgrade.php, version.php
=> Issue #152: Fixed database upgrade error.

settings.php
=> Issue #182: expiry_s change default to 1 month (30 * DAYSECS)

classes/output/tabs.php, classes/profile_table.php, lang/en/tool_excimer.php, settings.php, slowest.php, slowest_other.php
catalyst/moodle-tool_excimer#175 - split slowest script requests into multiple tabs #187 
task 1. build query enhancements [done]
task 2. Create tabbed page [done]
=> catalyst/moodle-tool_excimer#175 - split slowest script requests into multiple tabs
